version: '3'
services:
  acme:
    image: acmefactory:dev
    container_name: acme
    ports:
      - "9090:8080"
    command: "-Dlogback.configurationFile=logback.xml"
    #command: "-Dlogback.configurationFile=logback-debug.xml"
